# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8Av2NE-geNpdlv_SY7YDz4A5jVv5RbG
"""

import pandas as pd

df = pd.read_csv("base de datos limpia.csv")

df.head()