# -*- coding: utf-8 -*-
"""Código Base Limpia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1KH0s0V74HRjFjGXbGqYkSnKSHOINwh
"""

import pandas as pd

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv('/content/Áreas verdes por habitante en zonas urbanas (limpia).csv')

# Visualizar las primeras filas del DataFrame
df.head()