# -*- coding: utf-8 -*-
"""CALIDAD_AREAS_VERDES_DCT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OBiw68UJMu1rZ4RsiCy6pusmsBbhb3t
"""

import pandas as pd

df = pd.read_csv('/content/BASE_DE_DATOS_CALIDAD_ZONAS_VERDES.csv', sep=';')
df.head()